sudo: required
services:
  - docker

before_install:
  - docker build -t andremontenegroem/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andremontenegroem/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: docker-react
  env: Docker-react-env-2-env
  bucket_name: elasticbeanstalk-eu-central-1-527941870628
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
