sudo: required
services:
  - docker

before_install:
  - docker build -t andremontenegroem/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andremontenegroem/docker-react npm run test
